const siteList = [
    {
        "id" : 1 ,
        "websiteName" : "gov.uk",
        "outcomeUrl" : "https://gov.uk.glasswall-icap.com",
        "ip" : "51.11.8.179",
        "flavor" : "B: Docker v0.1",
        "openPorts" : "443",
        "os" : "Ubuntu 18.04 LTS",
        "infrastructure" : "GKE",
        "provisioning" : "Yes",
        "containerEngine" : "docker",
    },
    {
        "id" : 2 ,
        "websiteName" : "GW Engineering",
        "outcomeUrl" : "https://engineering.glasswallsolutions.com.glasswall-icap.com",
        "ip" : "54.170.84.172",
        "flavor" : "B: Docker v0.1",
        "openPorts" : "443",
        "os" : "Ubuntu 18.04 LTS",
        "infrastructure" : "CCE",
        "provisioning" : "Yes",
        "containerEngine" : "docker",
    },
    {
        "id" : 3 ,
        "websiteName" : "GW Website",
        "outcomeUrl" : "https://glasswallsolutions.com.glasswall-icap.com/",
        "ip" : "54.78.209.23",
        "flavor" : "A: K8s v0.1",
        "openPorts" : "443",
        "os" : "Ubuntu 18.04 LTS",
        "infrastructure" : "GKE",
        "provisioning" : "Yes",
        "containerEngine" : "RKT",
    },
    {
        "id" : 4 ,
        "websiteName" : "dataport.emma.msrb.org",
        "outcomeUrl" : "https://dataport.emma.msrb.org.glasswall-icap.com/Home/Index",
        "ip" : "3.120.30.57",
        "flavor" : "E: SOW v0.2",
        "openPorts" : "443",
        "os" : "Ubuntu 18.04 LTS",
        "infrastructure" : "CCE",
        "provisioning" : "Yes",
        "containerEngine" : "LXD",
    },
];

export default siteList;